--   
-- Help taken from [Hardball Times]http://www.hardballtimes.com/tht-live/building-a-retrosheet-database-the-short-form/
-- and [Baseball Hacks](http://examples.oreilly.com/9780596009427/)
--

USE `retrosheet`;

DROP TABLE IF EXISTS `games`;
CREATE TABLE         `games` (
  `game_id`                        VARCHAR(12)          DEFAULT NULL,
  `game_date`                      DATE                 NOT NULL,
  `game_start_time`                TIME                 NOT NULL DEFAULT "00:00:00",
  `year_id`                        INT(4)               NOT NULL DEFAULT '0',
  `game_dt`                        INT(11)              DEFAULT NULL,
  `game_ct`                        TINYINT(1)          DEFAULT NULL,
  --
  `away_team_id`                   VARCHAR(3)           DEFAULT NULL,
  `home_team_id`                   VARCHAR(3)           DEFAULT NULL,
  `park_id`                        VARCHAR(5)           DEFAULT NULL,
  --
  `away_start_pit_id`              VARCHAR(8)           DEFAULT NULL,  -- 10
  `home_start_pit_id`              VARCHAR(8)           DEFAULT NULL,  -- 11
  --
  `game_day_of_week`               VARCHAR(9)           DEFAULT NULL,  --  3
  `game_time_of_day`               INT(11)              DEFAULT NULL,  --  4
  `game_minutes_ct`                INT(11)              DEFAULT NULL,
  `inn_ct`                         INT(11)              DEFAULT NULL,
  `park_attendance`                INT(11)              DEFAULT NULL,
  `dh_fl`                          VARCHAR(1)           DEFAULT NULL,
  --
  `daynight_park_cd`               VARCHAR(1)           DEFAULT NULL,
  `temp_park_ct`                   INT(11)              DEFAULT NULL,
  `wind_direction_park_cd`         INT(11)              DEFAULT NULL,
  `wind_speed_park_ct`             INT(11)              DEFAULT NULL,
  `field_park_cd`                  INT(11)              DEFAULT NULL,
  `precip_park_cd`                 INT(11)              DEFAULT NULL,
  `sky_park_cd`                    INT(11)              DEFAULT NULL,
  --
  `away_score_ct`                  INT(3)              DEFAULT NULL,
  `home_score_ct`                  INT(3)              DEFAULT NULL,
  `away_hits_ct`                   INT(3)              DEFAULT NULL,
  `home_hits_ct`                   INT(3)              DEFAULT NULL,
  `away_err_ct`                    INT(3)              DEFAULT NULL,
  `home_err_ct`                    INT(3)              DEFAULT NULL,
  `away_lob_ct`                    INT(3)              DEFAULT NULL,
  `home_lob_ct`                    INT(3)              DEFAULT NULL,
  `win_pit_id`                     VARCHAR(8)           DEFAULT NULL,
  `lose_pit_id`                    VARCHAR(8)           DEFAULT NULL,
  `save_pit_id`                    VARCHAR(8)           DEFAULT NULL,
  `gwrbi_bat_id`                   VARCHAR(8)           DEFAULT NULL,
  --
  `away_lineup1_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup1_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup2_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup2_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup3_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup3_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup4_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup4_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup5_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup5_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup6_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup6_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup7_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup7_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup8_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup8_fld_cd`            INT(11)              DEFAULT NULL,
  `away_lineup9_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `away_lineup9_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup1_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup1_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup2_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup2_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup3_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup3_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup4_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup4_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup5_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup5_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup6_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup6_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup7_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup7_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup8_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup8_fld_cd`            INT(11)              DEFAULT NULL,
  `home_lineup9_bat_id`            VARCHAR(8)           DEFAULT NULL,
  `home_lineup9_fld_cd`            INT(11)              DEFAULT NULL,
  `away_finish_pit_id`             VARCHAR(8)           DEFAULT NULL,
  `home_finish_pit_id`             VARCHAR(8)           DEFAULT NULL,
  --
  `base4_ump_id`                   VARCHAR(8)           DEFAULT NULL,
  `base1_ump_id`                   VARCHAR(8)           DEFAULT NULL,
  `base2_ump_id`                   VARCHAR(8)           DEFAULT NULL,
  `base3_ump_id`                   VARCHAR(8)           DEFAULT NULL,
  `lf_ump_id`                      VARCHAR(8)           DEFAULT NULL,
  `rf_ump_id`                      VARCHAR(8)           DEFAULT NULL,
  `scorer_record_id`               VARCHAR(50)          DEFAULT NULL,
  `translator_record_id`           VARCHAR(50)          DEFAULT NULL,
  `inputter_record_id`             VARCHAR(50)          DEFAULT NULL,
  `input_record_ts`                VARCHAR(18)          DEFAULT NULL,
  `edit_record_ts`                 VARCHAR(18)          DEFAULT NULL,
  `method_record_cd`               VARCHAR(18)          DEFAULT NULL,
  `pitches_record_cd`              VARCHAR(1)           DEFAULT NULL,  -- 25
  --
  PRIMARY KEY `igame`         (`game_id`, `year_id`),
  UNIQUE KEY  `iteam_away`    (`away_team_id`, `year_id`, `game_date`, `game_ct`),
  UNIQUE KEY  `iteam_home`    (`home_team_id`, `year_id`, `game_date`, `game_ct`),
  UNIQUE KEY  `ipark`         (`park_id`,      `year_id`, `game_date`, `game_ct`),
  --
  KEY         `iyear_away`    (`year_id`, `away_team_id`),
  KEY         `iyear_home`    (`year_id`, `home_team_id`),
  KEY         `iyear_park`    (`year_id`, `park_id`),
  KEY         `pit_away`      (`away_start_pit_id`, `year_id`),
  KEY         `pit_home`      (`home_start_pit_id`, `year_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 /*!50100 PARTITION BY LIST (YEAR_ID) (PARTITION p1 VALUES IN (1921) ENGINE = MyISAM, PARTITION p2 VALUES IN (1922) ENGINE = MyISAM, PARTITION p3 VALUES IN (1952) ENGINE = MyISAM, PARTITION p4 VALUES IN (1953) ENGINE = MyISAM, PARTITION p5 VALUES IN (1954) ENGINE = MyISAM, PARTITION p6 VALUES IN (1955) ENGINE = MyISAM, PARTITION p7 VALUES IN (1956) ENGINE = MyISAM, PARTITION p8 VALUES IN (1957) ENGINE = MyISAM, PARTITION p9 VALUES IN (1958) ENGINE = MyISAM, PARTITION p10 VALUES IN (1959) ENGINE = MyISAM, PARTITION p11 VALUES IN (1960) ENGINE = MyISAM, PARTITION p12 VALUES IN (1961) ENGINE = MyISAM, PARTITION p13 VALUES IN (1962) ENGINE = MyISAM, PARTITION p14 VALUES IN (1963) ENGINE = MyISAM, PARTITION p15 VALUES IN (1964) ENGINE = MyISAM, PARTITION p16 VALUES IN (1965) ENGINE = MyISAM, PARTITION p17 VALUES IN (1966) ENGINE = MyISAM, PARTITION p18 VALUES IN (1967) ENGINE = MyISAM, PARTITION p19 VALUES IN (1968) ENGINE = MyISAM, PARTITION p20 VALUES IN (1969) ENGINE = MyISAM, PARTITION p21 VALUES IN (1970) ENGINE = MyISAM, PARTITION p22 VALUES IN (1971) ENGINE = MyISAM, PARTITION p23 VALUES IN (1972) ENGINE = MyISAM, PARTITION p24 VALUES IN (1973) ENGINE = MyISAM, PARTITION p25 VALUES IN (1974) ENGINE = MyISAM, PARTITION p26 VALUES IN (1975) ENGINE = MyISAM, PARTITION p27 VALUES IN (1976) ENGINE = MyISAM, PARTITION p28 VALUES IN (1977) ENGINE = MyISAM, PARTITION p29 VALUES IN (1978) ENGINE = MyISAM, PARTITION p30 VALUES IN (1979) ENGINE = MyISAM, PARTITION p31 VALUES IN (1980) ENGINE = MyISAM, PARTITION p32 VALUES IN (1981) ENGINE = MyISAM, PARTITION p33 VALUES IN (1982) ENGINE = MyISAM, PARTITION p34 VALUES IN (1983) ENGINE = MyISAM, PARTITION p35 VALUES IN (1984) ENGINE = MyISAM, PARTITION p36 VALUES IN (1985) ENGINE = MyISAM, PARTITION p37 VALUES IN (1986) ENGINE = MyISAM, PARTITION p38 VALUES IN (1987) ENGINE = MyISAM, PARTITION p39 VALUES IN (1988) ENGINE = MyISAM, PARTITION p40 VALUES IN (1989) ENGINE = MyISAM, PARTITION p41 VALUES IN (1990) ENGINE = MyISAM, PARTITION p42 VALUES IN (1991) ENGINE = MyISAM, PARTITION p43 VALUES IN (1992) ENGINE = MyISAM, PARTITION p44 VALUES IN (1993) ENGINE = MyISAM, PARTITION p45 VALUES IN (1994) ENGINE = MyISAM, PARTITION p46 VALUES IN (1995) ENGINE = MyISAM, PARTITION p47 VALUES IN (1996) ENGINE = MyISAM, PARTITION p48 VALUES IN (1997) ENGINE = MyISAM, PARTITION p49 VALUES IN (1998) ENGINE = MyISAM, PARTITION p50 VALUES IN (1999) ENGINE = MyISAM, PARTITION p51 VALUES IN (2000) ENGINE = MyISAM, PARTITION p52 VALUES IN (2001) ENGINE = MyISAM, PARTITION p53 VALUES IN (2002) ENGINE = MyISAM, PARTITION p54 VALUES IN (2003) ENGINE = MyISAM, PARTITION p55 VALUES IN (2004) ENGINE = MyISAM, PARTITION p56 VALUES IN (2005) ENGINE = MyISAM, PARTITION p57 VALUES IN (2006) ENGINE = MyISAM, PARTITION p58 VALUES IN (2007) ENGINE = MyISAM, PARTITION p59 VALUES IN (2008) ENGINE = MyISAM, PARTITION p60 VALUES IN (2009) ENGINE = MyISAM, PARTITION p61 VALUES IN (2010) ENGINE = MyISAM, PARTITION p62 VALUES IN (2011) ENGINE = MyISAM, PARTITION p63 VALUES IN (2012) ENGINE = MyISAM, PARTITION p64 VALUES IN (2013) ENGINE = MyISAM, PARTITION p65 VALUES IN (2014) ENGINE = MyISAM) */;

LOAD DATA INFILE '/Users/flip/ics/core/wukong/data/sports/baseball/retrosheet/raw/game_logs-1871-2013.csv'
REPLACE INTO TABLE `games`
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
IGNORE 1 ROWS
(
  game_dt,
  game_ct,
  game_day_of_week,
  game_time_of_day,
  dh_fl,
  daynight_park_cd,
  away_team_id,
  home_team_id,
  park_id,
  away_start_pit_id,
  home_start_pit_id,
  base4_ump_id,
  base1_ump_id,
  base2_ump_id,
  base3_ump_id,
  lf_ump_id,
  rf_ump_id,
  attend_park_ct,
  scorer_record_id,
  translator_record_id,
  inputter_record_id,
  input_record_ts,
  edit_record_ts,
  method_record_cd,
  pitches_record_cd,
  temp_park_ct,
  wind_direction_park_cd,
  wind_speed_park_ct,
  field_park_cd,
  precip_park_cd,
  sky_park_cd,
  minutes_game_ct,
  inn_ct,
  away_score_ct,
  home_score_ct,
  away_hits_ct,
  home_hits_ct,
  away_err_ct,
  home_err_ct,
  away_lob_ct,
  home_lob_ct,
  win_pit_id,
  lose_pit_id,
  save_pit_id,
  gwrbi_bat_id,
  away_lineup1_bat_id,
  away_lineup1_fld_cd,
  away_lineup2_bat_id,
  away_lineup2_fld_cd,
  away_lineup3_bat_id,
  away_lineup3_fld_cd,
  away_lineup4_bat_id,
  away_lineup4_fld_cd,
  away_lineup5_bat_id,
  away_lineup5_fld_cd,
  away_lineup6_bat_id,
  away_lineup6_fld_cd,
  away_lineup7_bat_id,
  away_lineup7_fld_cd,
  away_lineup8_bat_id,
  away_lineup8_fld_cd,
  away_lineup9_bat_id,
  away_lineup9_fld_cd,
  home_lineup1_bat_id,
  home_lineup1_fld_cd,
  home_lineup2_bat_id,
  home_lineup2_fld_cd,
  home_lineup3_bat_id,
  home_lineup3_fld_cd,
  home_lineup4_bat_id,
  home_lineup4_fld_cd,
  home_lineup5_bat_id,
  home_lineup5_fld_cd,
  home_lineup6_bat_id,
  home_lineup6_fld_cd,
  home_lineup7_bat_id,
  home_lineup7_fld_cd,
  home_lineup8_bat_id,
  home_lineup8_fld_cd,
  home_lineup9_bat_id,
  home_lineup9_fld_cd,
  away_finish_pit_id,
  home_finish_pit_id    
  )
  SET
    game_id   = CONCAT(home_team_id, game_dt, game_ct),
    game_date = STR_TO_DATE(game_dt, "%Y%m%d"),
    -- game_time = STR_TO_TIME(game_dt, game_time), "%Y%m%d%H%M%S"),
    year_ID   = LEFT(game_dt, 4)
  ;

  game_dt,
  game_ct,
  game_day_of_week,
  away_team_id,
  away_lg_id,
  away_game_idx,
  home_team_id,
  home_lg_id,
  home_game_idx,

  away_runs_ct,
  home_runs_ct,
  tot_outs_ct,
  game_daynight,
  completion_info,
  forfeit_info,
  protest_info,
  park_id,
  park_attendence,
  game_minutes_ct,
  away_linescore,
  home_linescore,

  away_AB,
  away_H,
  away_D,
  away_T,
  away_HR,
  away_RBI,
  away_SH,
  away_SF,
  away_HBP,
  away_BB,
  away_IBB,
  away_K,
  away_SB,
  away_CS,
  away_GDP,
  away_CI,
  away_LOB,
  away_pit_ids,
  away_ER,
  away_TER,
  away_WP,
  away_balks,
  away_PO,
  away_A,
  away_E,
  away_passed,
  away_DB,
  away_TP,

  home_AB,
  home_H,
  home_D,
  home_T,
  home_HR,
  home_RBI,
  home_SH,
  home_SF,
  home_HBP,
  home_BB,
  home_IBB,
  home_K,
  home_SB,
  home_CS,
  home_GDP,
  home_CI,
  home_LOB,
  home_pit_ids,
  home_ER,
  home_TER,
  home_WP,
  home_balks,
  home_PO,
  home_A,
  home_E,
  home_passed,
  home_DB,
  home_TP,

  ump_H_id,
  ump_H_name,
  ump_1B_ID,
  ump_1B_name,
  ump_2B_ID,
  ump_2B_name,
  ump_3B_ID,
  ump_3B_name,
  ump_LF_ID,
  ump_LF_name,
  ump_RF_ID,
  ump_RF_name,
  manager_away_id,
  manager_away_name,
  manager_home_id,
  manager_home_name,

  pit_win_ID,
  pit_win_name,
  pit_loss_id,
  pit_loss_name,
  pit_save_id,
  pit_save_name,
  bat_gwRBI_ID,
  bat_gwRBI_name,
  pit_away_start_id,
  pit_away_start_name,
  pit_home_start_id,
  pit_home_start_name,

  bat_away_1_ID,
  bat_away_1_name,
  bat_away_1_pos,
  bat_away_2_ID,
  bat_away_2_name,
  bat_away_2_pos,
  bat_away_3_ID,
  bat_away_3_name,
  bat_away_3_pos,
  bat_away_4_ID,
  bat_away_4_name,
  bat_away_4_pos,
  bat_away_5_ID,
  bat_away_5_name,
  bat_away_5_pos,
  bat_away_6_ID,
  bat_away_6_name,
  bat_away_6_pos,
  bat_away_7_ID,
  bat_away_7_name,
  bat_away_7_pos,
  bat_away_8_ID,
  bat_away_8_name,
  bat_away_8_pos,
  bat_away_9_ID,
  bat_away_9_name,
  bat_away_9_pos,

  bat_home_1_ID,
  bat_home_1_name,
  bat_home_1_pos,
  bat_home_2_ID,
  bat_home_2_name,
  bat_home_2_pos,
  bat_home_3_ID,
  bat_home_3_name,
  bat_home_3_pos,
  bat_home_4_ID,
  bat_home_4_name,
  bat_home_4_pos,
  bat_home_5_ID,
  bat_home_5_name,
  bat_home_5_pos,
  bat_home_6_ID,
  bat_home_6_name,
  bat_home_6_pos,
  bat_home_7_ID,
  bat_home_7_name,
  bat_home_7_pos,
  bat_home_8_ID,
  bat_home_8_name,
  bat_home_8_pos,
  bat_home_9_ID,
  bat_home_9_name,
  bat_home_9_pos,

  additional_info,
  acquisition_info                   

